tasks:
  - before: npm install ionic -g --save &&
            npm install &&
            npm audit fix &&
            npm rebuild node-sass --force &&
            npm update node-sass &&
            npm install @ionic/app-scripts@latest --save-dev &&
            npm i natives &&
            npm install --save @angular/material @angular/cdk @angular/animations &&
            npm install -g firebase-tools@6.1 a &&
            ionic cordova plugin add cordova-plugin-x-socialsharing &&
            npm install --save @ionic-native/social-sharing@4 &&
            ionic serve --external
  - init: npm run build

vscode:
  extensions:
    - kisstkondoros.vscode-gutter-preview@0.24.2:OkkUz1N4c4NtizGzg6XZzA==
    - vscode-icons-team.vscode-icons@9.7.0:vWMZFN0zy+UAVL2V5iuz4A==
    - afmicc.GetterAndSetterGenerator@1.0.2:Ds9Su3I4Hxy7UWjM+Kmq5g==
    - danielehrhardt.ionic3-vs-ionView-snippets@1.0.2:uzc1eO7+aKYGMnGVr7VRVQ==
    - GitHub.vscode-pull-request-github@0.14.0:mWimTWZmKmr/E8TpSSxulA==
